name: Build and Push Docker Image to GCP Artifact Registry
 
on:
  push:
    branches:
      - main
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
 
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
 
    - name: Authenticate to Google Cloud
      id: auth
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
 
    - name: Configure Docker to use the Artifact Registry repository
      run: |
gcloud auth configure-docker us-west1-docker.pkg.dev
 
    - name: Build Docker image
      run: |
docker build -t us-west1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$TAG .
 
    - name: Push Docker image to Artifact Registry
      run: |
docker push us-central1-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$IMAGE_NAME:$TAG
 
    env:
      PROJECT_ID: ferrous-tine-424803-c4
      REPO_NAME: build-infra
      IMAGE_NAME: build-infra
      TAG: latest